/* Palette generated by Material Palette  materialpalette.com/bluegrey/indigo */

export const darkPrimary= "#455A64";
export const primary= "#607D8B";
export const lightPrimary= "#CFD8DC";
export const textPrimary= "#FFFFFF";
export const accent= "#536DFE";
export const primaryText= "#212121";
export const secondaryText= "#757575";
export const divider= "#BDBDBD";
