export const ADD_CALL = 'ADD_CALL'
export const DELETE_CALL = 'DELETE_CALL'
export const EDIT_TYPE = 'EDIT_TYPE'

export const UPDATE_DISPATCHED = 'UPDATE_DISPATCHED'
export const UPDATE_ARRIVED = 'UPDATE_ARRIVED'

export const COMPLETE_CALL = 'COMPLETE_CALL'

export const COMPLETE_ALL = 'COMPLETE_ALL'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'

//COMMENTS
export const ADD_COMMENT = 'ADD_COMMENT'
